/** Reviewed, source-controlled identifiers that may cross the telemetry boundary. */
const TELEMETRY_ADDITIONS = {
  areas: ["agenda", "command_palette", "debrief", "dispatch", "entity_search", "literature", "navigation", "objectives"],
  operations: ["add", "add_paper_to_pipeline", "ask_axis", "biometric_gate_settings_lookup", "check_conflicts", "check_local_conflicts", "capture_signal", "create_note_from_paper", "daily_summary", "delete_external_event", "delete_signal", "embedding_generate", "embedding_note_lookup", "embedding_upsert", "full_page_navigation", "install", "list_composio_accounts", "list_composio_calendar_accounts", "list_connections", "list_external_events", "load_daily_entry", "load_daily_history", "load_event_for_calendar_sync", "load_token", "log_key_result_progress", "manage_signal", "persist_cache", "persist_cache_failure_state", "persist_external_event_ids", "persist_failure_state", "persist_reconciliation_state", "pipeline_stage_insert", "pipeline_stage_lookup", "preview", "preview_network", "preview_parse", "quick", "read_cache", "reference_delete", "reference_delete_network", "reference_write", "remove", "reply", "resolve_team", "revoke_token", "route_signal", "route_to_pipeline", "route_to_pipeline_stage", "route_to_signal", "run_concentration_check", "run_routine", "save_daily_entry", "save_paper_meta", "save_token", "save_weekly_reflection", "scan_platform", "schedule_task", "semantic_search_embed", "semantic_search_notes", "semantic_search_rpc", "send", "shell_profile_lookup", "start_scenario", "stop_scenario", "suggest_task", "sync_event", "transcribe_audio", "triage_all", "triage_signal", "update_cache", "update_external_event", "usage_write", "weekly_summary", "workspace_open", "write_calendar_event_cache"],
  codes: ["APPROVAL_CREATE_FAILED", "APPROVAL_MUTATION_UNAVAILABLE", "APPROVAL_UPDATE_FAILED", "ENCODE_FAILED", "PANE_LIMIT", "PROVIDER_ERROR", "PROVIDER_FALLBACK", "PROVIDER_RATE_LIMITED", "REFERENCES_UNAVAILABLE", "SPOTIFY_DENIED", "SPOTIFY_MISSING_CODE", "SPOTIFY_STATE_MISMATCH", "SPOTIFY_STATE_MISSING", "SPOTIFY_TOKEN_EXCHANGE_FAILED", "TASK_CREATE_FAILED", "TASK_MUTATION_UNAVAILABLE", "TASK_UPDATE_FAILED", "UNAVAILABLE", "UNEXPECTED_OK", "auth_expired", "encryption_failed", "invalid_request", "not_found", "not_supported", "outbox_encryption_unavailable", "schema_validation", "unknown"],
} as const;
const AXIS_TELEMETRY_VOCABULARY_BASE = {
  areas: ["ai", "approvals", "auth", "calendar", "console", "cron", "fund", "integrations", "mail", "memory", "notes", "profile", "routines", "safe-fetch", "schedule", "search", "tasks", "vector", "vitality", "widgets", "workspace", ...TELEMETRY_ADDITIONS.areas],
  providers: ["ai", "anthropic", "artic", "composio", "gemini", "gmail", "google", "make", "manual", "open-meteo", "outlook", "plaid", "poetrydb", "polygon", "public", "spotify", "strava", "supabase", "youtube"],
  transports: ["composio", "direct"],
  operations: ["accounts", "air_quality", "archive", "artwork_search", "balances", "briefing_feed", "build_options", "cached_feed", "challenge_cleanup", "challenge_consume", "challenge_insert", "check_authenticator_assurance", "clear_session", "commit_authentication", "complete_oauth", "complete_run", "configure_market_data", "consume_challenge", "create", "create_event", "create_passkey", "daily_balance", "daylight", "decision_event", "delete", "delete_event", "delete_passkey", "detail_activity", "disconnect", "disconnect_cache_cleanup", "disconnect_cleanup", "disconnect_load", "download_mail_attachment", "event", "execute", "execute_claimed_resume", "execution_event", "fetch_news_sources", "fetch_quote", "fetch_widget", "find_free_slots", "free_busy", "gemini_generate", "generate", "generate_report", "get", "get_message", "get_scenario", "initiate_connection", "insert_signal", "issue_session", "list", "list_accounts", "list_events", "list_organizations", "list_passkeys", "list_scenarios", "list_teams", "load", "load_approval", "load_credentials", "load_passkey", "load_passkeys", "load_session_owner", "load_webhook_connection", "lookup", "lookup_existing_signal", "objectives_scan", "og_image_meta", "og_image_resolve", "og_image_stream", "options", "order_history", "outbox_list", "outbox_owner_lookup", "outbox_replay", "outbox_replay_confirmation", "outbox_replay_persist", "persist_blocked_run", "persist_failed_step", "persist_report", "persist_step", "poem_fetch", "positions", "rate_limit", "rate_limit_backend", "read", "read_cache_fallback", "read_connection_status", "read_research_context", "reader_extract", "record", "record_step_failure", "redeem_session", "reference_resolution", "references", "refresh", "refresh_connection", "resolve", "run_scenario", "runtime_event", "save", "save_attachment_to_library", "save_attachment_to_library_metadata", "save_attachment_to_library_storage", "search", "serialize", "stamp", "start_oauth", "start_run", "status", "store_challenge", "sync_inbox", "sync_transactions", "transactions", "transition", "trigger_webhook", "update", "upsert_connection", "usage", "verify", "verify_cookie_session", "verify_owner", "weather", "web_proxy", "webhook_sync", "write_cache", "youtube_caption", "youtube_watch_page", ...TELEMETRY_ADDITIONS.operations],
  codes: ["APPROVAL_CONFLICT", "APPROVAL_POLICY_INVALID", "APPROVAL_UNAVAILABLE", "AUTH_ASSURANCE_UNAVAILABLE", "CHALLENGE_CONSUME_FAILED", "CHALLENGE_STORE_FAILED", "CONFLICT", "COUNTER_CONFLICT", "CREDENTIAL_EXISTS", "HOLDINGS_UNAVAILABLE", "INVALID_ACTION_CLASS", "INVALID_BODY", "INVALID_HOLDING", "INVALID_QUERY", "INVALID_RESPONSE", "MARKET_DATA_INCOMPLETE", "MARKET_DATA_REQUIRED", "MEMORY_ARCHIVE_FAILED", "MEMORY_CREATE_FAILED", "MEMORY_LIST_FAILED", "MEMORY_UPDATE_FAILED", "NOT_CONFIGURED", "NOT_FOUND", "NO_REDIRECT_URL", "PASSKEYS_UNAVAILABLE", "PASSKEY_COMMIT_FAILED", "PASSKEY_CREATE_FAILED", "PASSKEY_DELETE_FAILED", "PASSKEY_LIST_FAILED", "PASSKEY_NOT_FOUND", "PASSKEY_OPTIONS_FAILED", "PASSKEY_SERVICE_UNAVAILABLE", "PASSKEY_SESSION_CLEANUP_FAILED", "PASSKEY_SESSION_UNAVAILABLE", "PROFILE_ACCOUNT_UNAVAILABLE", "PROFILE_AVATAR_UNAVAILABLE", "PROFILE_LOAD_FAILED", "PROFILE_SAVE_FAILED", "PROVIDER_TIMEOUT", "RATE_LIMIT_BACKEND_FAILED", "RPC_FAILED", "RUN_BLOCKED", "RUN_BLOCK_PERSISTENCE_FAILED", "RUN_COMPLETION_FAILED", "RUN_START_FAILED", "SAFE_FETCH_ABORTED", "SAFE_FETCH_BLOCKED_ADDRESS", "SAFE_FETCH_BLOCKED_HOST", "SAFE_FETCH_BODY_TOO_LARGE", "SAFE_FETCH_DNS_FAILED", "SAFE_FETCH_INVALID_REDIRECT", "SAFE_FETCH_INVALID_URL", "SAFE_FETCH_ROUTE_FAILED", "SAFE_FETCH_TIMEOUT", "SAFE_FETCH_TOO_MANY_REDIRECTS", "SAFE_FETCH_TRANSPORT_FAILED", "SAVE_SCHEMA_NEWER", "SERVICE_UNAVAILABLE", "SOURCE_UNAVAILABLE", "SPOTIFY_NOT_CONFIGURED", "STEP_PERSISTENCE_FAILED", "STEP_UP_UNAVAILABLE", "STEP_UP_UPDATE_FAILED", "TASK_ACTIVITY_UNAVAILABLE", "UNAUTHORIZED", "USAGE_UNAVAILABLE", "VECTOR_BOOTSTRAP_RESPONSE_INVALID", "VECTOR_BOOTSTRAP_RESPONSE_TOO_LARGE", "VECTOR_BOOTSTRAP_UNAVAILABLE", "VECTOR_CHECKSUM_MISMATCH", "VECTOR_CONFLICT_AUTH_REQUIRED", "VECTOR_CONFLICT_NOT_OPEN", "VECTOR_CONFLICT_REFRESH_FAILED", "VECTOR_CONFLICT_RESOLVE_FAILED", "VECTOR_CONFLICT_RESPONSE_MISMATCH", "VECTOR_CONFLICT_UNAVAILABLE", "VECTOR_EVENT_SYNC_FAILED", "VECTOR_EVENT_TOO_LARGE", "VECTOR_OWNER_CHANGED", "VECTOR_RATE_LIMIT_UNAVAILABLE", "VECTOR_RUNTIME_EVENT_INVALID", "VECTOR_SAVE_SYNC_FAILED", "VECTOR_SAVE_TOO_LARGE", "VECTOR_SETTING_CLOCK_FUTURE", "VECTOR_SYNC_REFRESH_FAILED", "VECTOR_SYNC_RESPONSE_INVALID", "account_status_unavailable", "cache_unavailable", "connection_lookup_failed", "network", "provider_error", "rate_limited", "semantic_error", "semantic_unavailable", "timeout", ...TELEMETRY_ADDITIONS.codes],
} as const;

export const AXIS_TELEMETRY_VOCABULARY = {
  ...AXIS_TELEMETRY_VOCABULARY_BASE,
  operations: [
    ...AXIS_TELEMETRY_VOCABULARY_BASE.operations,
    "authenticate_request",
    "resolve_optional_session",
  ],
  codes: [
    ...AXIS_TELEMETRY_VOCABULARY_BASE.codes,
    "AUTH_BACKEND_UNAVAILABLE",
    "AUTH_CONFIGURATION_UNAVAILABLE",
  ],
} as const;

export const AXIS_TELEMETRY_SETS = {
  areas: new Set<string>(AXIS_TELEMETRY_VOCABULARY.areas),
  providers: new Set<string>(AXIS_TELEMETRY_VOCABULARY.providers),
  transports: new Set<string>(AXIS_TELEMETRY_VOCABULARY.transports),
  operations: new Set<string>(AXIS_TELEMETRY_VOCABULARY.operations),
  codes: new Set<string>(AXIS_TELEMETRY_VOCABULARY.codes),
};
