/**
 * Checked-in review baseline for nonliteral telemetry metadata. The test compares
 * this array (including duplicate occurrences) to a fresh AST walk. Do not
 * regenerate blindly: each added line is a new reviewable data shape.
 */
export const AXIS_DYNAMIC_TELEMETRY_BASELINE: readonly string[] = [
  "src/app/api/agent-tasks/[id]/route.ts|code|shorthand:code",
  "src/app/api/agent-tasks/[id]/route.ts|status|shorthand:status",
  "src/app/api/agent-tasks/route.ts|code|shorthand:code",
  "src/app/api/agent-tasks/route.ts|status|shorthand:status",
  "src/app/api/ai/route.ts|code|ternary:rateLimited ? \"PROVIDER_RATE_LIMITED\" : \"PROVIDER_ERROR\"",
  "src/app/api/ai/route.ts|provider|identifier:telemetryProvider",
  "src/app/api/ai/route.ts|status|ternary:rateLimited ? 429 : 502",
  "src/app/api/approvals/[id]/route.ts|code|shorthand:code",
  "src/app/api/approvals/[id]/route.ts|code|shorthand:code",
  "src/app/api/approvals/[id]/route.ts|status|shorthand:status",
  "src/app/api/approvals/[id]/route.ts|status|shorthand:status",
  "src/app/api/approvals/[id]/step-up/route.ts|status|ternary:consumedChallenge.code === \"SERVICE_UNAVAILABLE\" ? 503 : 500",
  "src/app/api/approvals/route.ts|code|shorthand:code",
  "src/app/api/approvals/route.ts|status|shorthand:status",
  "src/app/api/auth/passkey/authenticate/route.ts|route|identifier:ROUTE",
  "src/app/api/auth/passkey/authenticate/route.ts|route|identifier:ROUTE",
  "src/app/api/auth/passkey/authenticate/route.ts|route|identifier:ROUTE",
  "src/app/api/auth/passkey/authenticate/route.ts|route|identifier:ROUTE",
  "src/app/api/auth/passkey/authenticate/route.ts|route|identifier:ROUTE",
  "src/app/api/auth/passkey/authenticate/route.ts|route|identifier:ROUTE",
  "src/app/api/auth/passkey/authenticate/route.ts|route|identifier:ROUTE",
  "src/app/api/auth/passkey/authenticate/route.ts|route|identifier:ROUTE",
  "src/app/api/auth/passkey/authenticate/route.ts|route|identifier:ROUTE",
  "src/app/api/auth/passkey/authenticate/route.ts|route|identifier:ROUTE",
  "src/app/api/auth/passkey/authenticate/route.ts|route|identifier:ROUTE",
  "src/app/api/auth/passkey/authenticate/route.ts|route|identifier:ROUTE",
  "src/app/api/auth/passkey/authenticate/route.ts|route|identifier:ROUTE",
  "src/app/api/auth/passkey/authenticate/route.ts|status|ternary:committed.code === \"SERVICE_UNAVAILABLE\" ? 503 : 500",
  "src/app/api/auth/passkey/authenticate/route.ts|status|ternary:consumed.code === \"SERVICE_UNAVAILABLE\" ? 503 : 500",
  "src/app/api/auth/passkey/delete/route.ts|status|shorthand:status",
  "src/app/api/auth/passkey/register/route.ts|route|identifier:ROUTE",
  "src/app/api/auth/passkey/register/route.ts|route|identifier:ROUTE",
  "src/app/api/auth/passkey/register/route.ts|route|identifier:ROUTE",
  "src/app/api/auth/passkey/register/route.ts|route|identifier:ROUTE",
  "src/app/api/auth/passkey/register/route.ts|route|identifier:ROUTE",
  "src/app/api/auth/passkey/register/route.ts|route|identifier:ROUTE",
  "src/app/api/auth/passkey/register/route.ts|route|identifier:ROUTE",
  "src/app/api/auth/passkey/register/route.ts|status|ternary:consumed.code === \"SERVICE_UNAVAILABLE\" ? 503 : 500",
  "src/app/api/auth/passkey/register/route.ts|status|ternary:created.code === \"SERVICE_UNAVAILABLE\" ? 503 : 500",
  "src/app/api/auth/preferences/route.ts|code|ternary:operation === \"read\" ? \"PROFILE_LOAD_FAILED\" : \"PROFILE_SAVE_FAILED\"",
  "src/app/api/auth/preferences/route.ts|operation|shorthand:operation",
  "src/app/api/auth/preferences/route.ts|route|identifier:ROUTE",
  "src/app/api/auth/profile/route.ts|operation|shorthand:operation",
  "src/app/api/auth/profile/route.ts|route|identifier:ROUTE",
  "src/app/api/auth/settings/route.ts|code|shorthand:code",
  "src/app/api/auth/settings/route.ts|operation|shorthand:operation",
  "src/app/api/auth/settings/route.ts|route|identifier:ROUTE",
  "src/app/api/brokerage/accounts/route.ts|status|property:res.status",
  "src/app/api/brokerage/order-history/route.ts|status|property:res.status",
  "src/app/api/brokerage/orders/route.ts|code|property:prepared.error.code",
  "src/app/api/brokerage/orders/route.ts|code|property:result.error.code",
  "src/app/api/brokerage/orders/route.ts|code|property:result.error.code",
  "src/app/api/brokerage/orders/route.ts|code|ternary:approvalId ? \"not_supported\" : result?.ok ? \"UNEXPECTED_OK\" : result?.error.code",
  "src/app/api/brokerage/positions/route.ts|status|property:res.status",
  "src/app/api/calendar/event/[id]/route.ts|op|shorthand:op",
  "src/app/api/calendar/event/[id]/route.ts|partial|expression:errors.length > 0 || notSupported.length > 0",
  "src/app/api/calendar/event/[id]/route.ts|partial|identifier:calendarCleanupFailed",
  "src/app/api/calendar/event/[id]/route.ts|provider|identifier:source",
  "src/app/api/calendar/event/[id]/route.ts|provider|property:err.source",
  "src/app/api/calendar/event/[id]/route.ts|provider|property:error.source",
  "src/app/api/calendar/event/[id]/route.ts|transport|property:err.transport",
  "src/app/api/calendar/event/[id]/route.ts|transport|property:error.transport",
  "src/app/api/calendar/external/route.ts|code|property:err.code",
  "src/app/api/calendar/external/route.ts|partial|expression:errors.length > 0 || cachePersistenceError",
  "src/app/api/calendar/external/route.ts|provider|identifier:source",
  "src/app/api/calendar/external/route.ts|provider|property:err.source",
  "src/app/api/calendar/external/route.ts|transport|property:err.transport",
  "src/app/api/calendar/sync/route.ts|code|property:err.code",
  "src/app/api/calendar/sync/route.ts|partial|expression:errors.length > 0",
  "src/app/api/calendar/sync/route.ts|provider|identifier:source",
  "src/app/api/calendar/sync/route.ts|provider|property:err.source",
  "src/app/api/calendar/sync/route.ts|transport|property:err.transport",
  "src/app/api/cron/daily/route.ts|operation|shorthand:operation",
  "src/app/api/cron/feed-digest/route.ts|operation|shorthand:operation",
  "src/app/api/cron/intelligence-sweep/route.ts|level|expression:\"error\" as const",
  "src/app/api/cron/intelligence-sweep/route.ts|operation|shorthand:operation",
  "src/app/api/embeddings/route.ts|supabase_code|expression:noteError.code ?? \"unknown\"",
  "src/app/api/embeddings/route.ts|supabase_code|expression:upsertError.code ?? \"unknown\"",
  "src/app/api/entities/[kind]/[id]/route.ts|code|property:resolved.error.code",
  "src/app/api/entities/[kind]/[id]/usage/route.ts|code|property:resolved.error.code",
  "src/app/api/entities/search/route.ts|code|property:failure.code",
  "src/app/api/entity-references/route.ts|code|property:unavailable.error.code",
  "src/app/api/fund/advisor/route.ts|operation|shorthand:operation",
  "src/app/api/fund/report/route.ts|route|identifier:ROUTE",
  "src/app/api/fund/report/route.ts|route|identifier:ROUTE",
  "src/app/api/fund/report/route.ts|route|identifier:ROUTE",
  "src/app/api/fund/report/route.ts|route|identifier:ROUTE",
  "src/app/api/integrations/composio/connect/route.ts|status|shorthand:status",
  "src/app/api/integrations/composio/disconnect/route.ts|attempted|property:targets.length",
  "src/app/api/integrations/composio/disconnect/route.ts|disconnected|property:deletedIds.length",
  "src/app/api/integrations/composio/disconnect/route.ts|failed|property:failures.length",
  "src/app/api/integrations/composio/status/route.ts|status|expression:errorStatus(err)",
  "src/app/api/integrations/make/outbox/route.ts|code|property:error.code",
  "src/app/api/mail/inbox/route.ts|partial|expression:true",
  "src/app/api/mail/message/[id]/action/route.ts|code|property:result.error.code",
  "src/app/api/mail/message/[id]/action/route.ts|code|property:result.error.code",
  "src/app/api/mail/message/[id]/action/route.ts|operation|identifier:action",
  "src/app/api/mail/message/[id]/action/route.ts|provider|shorthand:provider",
  "src/app/api/mail/message/[id]/action/route.ts|provider|shorthand:provider",
  "src/app/api/mail/message/[id]/action/route.ts|provider|shorthand:provider",
  "src/app/api/mail/message/[id]/action/route.ts|provider|shorthand:provider",
  "src/app/api/mail/message/[id]/action/route.ts|provider|shorthand:provider",
  "src/app/api/mail/message/[id]/action/route.ts|status|expression:result.error.status ?? status",
  "src/app/api/mail/message/[id]/action/route.ts|status|ternary:isTimeout ? 504 : 502",
  "src/app/api/mail/message/[id]/action/route.ts|transport|shorthand:transport",
  "src/app/api/mail/message/[id]/action/route.ts|transport|shorthand:transport",
  "src/app/api/mail/message/[id]/action/route.ts|transport|shorthand:transport",
  "src/app/api/mail/message/[id]/action/route.ts|transport|shorthand:transport",
  "src/app/api/mail/message/[id]/action/route.ts|transport|shorthand:transport",
  "src/app/api/mail/message/[id]/route.ts|code|property:attachmentResult.error.code",
  "src/app/api/mail/message/[id]/route.ts|code|property:result.error.code",
  "src/app/api/mail/message/[id]/route.ts|code|property:result.error.code",
  "src/app/api/mail/message/[id]/route.ts|code|property:result.error.code",
  "src/app/api/mail/message/[id]/route.ts|code|property:result.error.code",
  "src/app/api/mail/message/[id]/route.ts|code|ternary:isTimeout ? \"timeout\" : \"network\"",
  "src/app/api/mail/message/[id]/route.ts|code|ternary:isTimeout ? \"timeout\" : \"network\"",
  "src/app/api/mail/message/[id]/route.ts|code|ternary:isTimeout ? \"timeout\" : \"network\"",
  "src/app/api/mail/message/[id]/route.ts|operation|property:body.action",
  "src/app/api/mail/message/[id]/route.ts|operation|property:body.action",
  "src/app/api/mail/message/[id]/route.ts|operation|property:body.action",
  "src/app/api/mail/message/[id]/route.ts|operation|property:body.action",
  "src/app/api/mail/message/[id]/route.ts|provider|shorthand:provider",
  "src/app/api/mail/message/[id]/route.ts|provider|shorthand:provider",
  "src/app/api/mail/message/[id]/route.ts|provider|shorthand:provider",
  "src/app/api/mail/message/[id]/route.ts|provider|shorthand:provider",
  "src/app/api/mail/message/[id]/route.ts|provider|shorthand:provider",
  "src/app/api/mail/message/[id]/route.ts|provider|shorthand:provider",
  "src/app/api/mail/message/[id]/route.ts|provider|shorthand:provider",
  "src/app/api/mail/message/[id]/route.ts|provider|shorthand:provider",
  "src/app/api/mail/message/[id]/route.ts|provider|shorthand:provider",
  "src/app/api/mail/message/[id]/route.ts|provider|shorthand:provider",
  "src/app/api/mail/message/[id]/route.ts|provider|shorthand:provider",
  "src/app/api/mail/message/[id]/route.ts|provider|shorthand:provider",
  "src/app/api/mail/message/[id]/route.ts|provider|shorthand:provider",
  "src/app/api/mail/message/[id]/route.ts|provider|shorthand:provider",
  "src/app/api/mail/message/[id]/route.ts|status|expression:result.error.status ?? status",
  "src/app/api/mail/message/[id]/route.ts|status|shorthand:status",
  "src/app/api/mail/message/[id]/route.ts|status|shorthand:status",
  "src/app/api/mail/message/[id]/route.ts|status|ternary:isTimeout ? 504 : 502",
  "src/app/api/mail/message/[id]/route.ts|transport|shorthand:transport",
  "src/app/api/mail/message/[id]/route.ts|transport|shorthand:transport",
  "src/app/api/mail/message/[id]/route.ts|transport|shorthand:transport",
  "src/app/api/mail/message/[id]/route.ts|transport|shorthand:transport",
  "src/app/api/mail/message/[id]/route.ts|transport|shorthand:transport",
  "src/app/api/mail/message/[id]/route.ts|transport|shorthand:transport",
  "src/app/api/mail/message/[id]/route.ts|transport|shorthand:transport",
  "src/app/api/mail/message/[id]/route.ts|transport|shorthand:transport",
  "src/app/api/mail/message/[id]/route.ts|transport|shorthand:transport",
  "src/app/api/mail/message/[id]/route.ts|transport|shorthand:transport",
  "src/app/api/mail/message/[id]/route.ts|transport|shorthand:transport",
  "src/app/api/mail/message/[id]/route.ts|transport|shorthand:transport",
  "src/app/api/mail/send/route.ts|code|property:result.error.code",
  "src/app/api/mail/send/route.ts|code|property:result.error.code",
  "src/app/api/mail/send/route.ts|code|property:result.error.code",
  "src/app/api/mail/send/route.ts|code|ternary:isTimeout ? \"timeout\" : \"network\"",
  "src/app/api/mail/send/route.ts|operation|shorthand:operation",
  "src/app/api/mail/send/route.ts|op|ternary:inReplyTo ? \"reply\" : \"send\"",
  "src/app/api/mail/send/route.ts|provider|shorthand:provider",
  "src/app/api/mail/send/route.ts|provider|shorthand:provider",
  "src/app/api/mail/send/route.ts|provider|shorthand:provider",
  "src/app/api/mail/send/route.ts|provider|shorthand:provider",
  "src/app/api/mail/send/route.ts|provider|shorthand:provider",
  "src/app/api/mail/send/route.ts|status|expression:String(status)",
  "src/app/api/mail/send/route.ts|status|expression:result.error.status ?? status",
  "src/app/api/mail/send/route.ts|transport|shorthand:transport",
  "src/app/api/mail/send/route.ts|transport|shorthand:transport",
  "src/app/api/mail/send/route.ts|transport|shorthand:transport",
  "src/app/api/mail/send/route.ts|transport|shorthand:transport",
  "src/app/api/mail/send/route.ts|transport|shorthand:transport",
  "src/app/api/mail/sync/route.ts|code|property:result.error.code",
  "src/app/api/mail/sync/route.ts|partial|expression:errors.length > 0",
  "src/app/api/mail/sync/route.ts|provider|property:account.provider",
  "src/app/api/mail/sync/route.ts|provider|property:account.provider",
  "src/app/api/mail/sync/route.ts|status|expression:result.error.status ?? mailErrorStatus(result.error.code)",
  "src/app/api/mail/sync/route.ts|transport|shorthand:transport",
  "src/app/api/mail/sync/route.ts|transport|shorthand:transport",
  "src/app/api/massive/history/route.ts|status|shorthand:status",
  "src/app/api/massive/movers/route.ts|failed|shorthand:failed",
  "src/app/api/massive/movers/route.ts|partial|expression:failed > 0",
  "src/app/api/massive/quote/route.ts|status|shorthand:status",
  "src/app/api/massive/quote/route.ts|status|shorthand:status",
  "src/app/api/massive/search/route.ts|status|shorthand:status",
  "src/app/api/massive/snapshot/route.ts|status|shorthand:status",
  "src/app/api/notes/transcribe/route.ts|status|expression:String(res.status)",
  "src/app/api/plaid/balances/route.ts|status|property:res.status",
  "src/app/api/plaid/transactions/route.ts|status|property:res.status",
  "src/app/api/plaid/webhook/route.ts|error_code|property:result.error",
  "src/app/api/profile/avatar/route.ts|operation|shorthand:operation",
  "src/app/api/profile/avatar/route.ts|route|identifier:ROUTE",
  "src/app/api/routines/concentration-check/route.ts|code|identifier:errorCode",
  "src/app/api/routines/concentration-check/route.ts|shape|spread:expression:(runId ? { runId } : {})",
  "src/app/api/routines/rebalance-proposal/route.ts|code|property:blocked.code",
  "src/app/api/routines/rebalance-proposal/route.ts|operation|property:blocked.operation",
  "src/app/api/routines/rebalance-proposal/route.ts|provider|property:adapter.provider",
  "src/app/api/routines/rebalance-proposal/route.ts|provider|property:adapter.provider",
  "src/app/api/routines/rebalance-proposal/route.ts|provider|property:adapter.provider",
  "src/app/api/routines/rebalance-proposal/route.ts|route|identifier:ROUTE",
  "src/app/api/routines/rebalance-proposal/route.ts|route|identifier:ROUTE",
  "src/app/api/routines/rebalance-proposal/route.ts|route|identifier:ROUTE",
  "src/app/api/routines/rebalance-proposal/route.ts|route|identifier:ROUTE",
  "src/app/api/routines/rebalance-proposal/route.ts|route|identifier:ROUTE",
  "src/app/api/routines/rebalance-proposal/route.ts|route|identifier:ROUTE",
  "src/app/api/routines/rebalance-proposal/route.ts|shape|spread:property:blocked.tags",
  "src/app/api/routines/rebalance-proposal/route.ts|status|property:blocked.status",
  "src/app/api/routines/runs/[id]/resume/route.ts|code|identifier:errorCode",
  "src/app/api/routines/runs/[id]/resume/route.ts|code|property:failure.code",
  "src/app/api/routines/runs/[id]/resume/route.ts|operation|shorthand:operation",
  "src/app/api/routines/runs/[id]/resume/route.ts|status|shorthand:status",
  "src/app/api/search/quick/route.ts|queryLength|property:q.length",
  "src/app/api/search/semantic/route.ts|supabase_code|expression:error.code ?? \"unknown\"",
  "src/app/api/search/semantic/route.ts|supabase_code|expression:notesError.code ?? \"unknown\"",
  "src/app/api/spotify/callback/route.ts|code|element:SPOTIFY_FAILURE_CODES[reason]",
  "src/app/api/spotify/callback/route.ts|status|shorthand:status",
  "src/app/api/strava/_lib.ts|operation|expression:path.split(\"?\")[0].split(\"/\").filter(Boolean).join(\"_\") || \"request\"",
  "src/app/api/strava/_lib.ts|shape|spread:expression:(init?.headers ?? {})",
  "src/app/api/strava/_lib.ts|shape|spread:identifier:init",
  "src/app/api/vector/bootstrap/route.ts|route|identifier:ROUTE",
  "src/app/api/vector/bootstrap/route.ts|route|identifier:ROUTE",
  "src/app/api/vector/bootstrap/route.ts|route|identifier:ROUTE",
  "src/app/api/vector/bootstrap/route.ts|route|identifier:ROUTE",
  "src/app/api/vector/conflicts/[id]/route.ts|route|identifier:ROUTE",
  "src/app/api/vector/conflicts/[id]/route.ts|route|identifier:ROUTE",
  "src/app/api/vector/conflicts/[id]/route.ts|route|identifier:ROUTE",
  "src/app/api/vector/conflicts/[id]/route.ts|route|identifier:ROUTE",
  "src/app/api/vector/conflicts/[id]/route.ts|route|identifier:ROUTE",
  "src/app/api/vector/sync/route.ts|route|identifier:ROUTE",
  "src/app/api/vector/sync/route.ts|route|identifier:ROUTE",
  "src/app/api/vector/sync/route.ts|route|identifier:ROUTE",
  "src/app/api/vector/sync/route.ts|route|identifier:ROUTE",
  "src/app/api/vector/sync/route.ts|route|identifier:ROUTE",
  "src/app/api/widgets/agenda/route.ts|failed|expression:errors.join(\",\")",
  "src/app/api/widgets/agenda/route.ts|partial|expression:false",
  "src/app/api/widgets/agenda/route.ts|partial|expression:true",
  "src/app/api/widgets/air-quality/route.ts|fallback|expression:false",
  "src/app/api/widgets/air-quality/route.ts|fallback|expression:true",
  "src/app/api/widgets/art/route.ts|fallback|expression:false",
  "src/app/api/widgets/art/route.ts|fallback|expression:true",
  "src/app/api/widgets/batch/route.ts|code|property:batchError.code",
  "src/app/api/widgets/batch/route.ts|code|property:cacheError.code",
  "src/app/api/widgets/batch/route.ts|code|property:cacheReadError.code",
  "src/app/api/widgets/batch/route.ts|code|property:error.code",
  "src/app/api/widgets/batch/route.ts|failed|property:Object.keys(errors).length",
  "src/app/api/widgets/batch/route.ts|provider|property:definition.source.provider",
  "src/app/api/widgets/batch/route.ts|provider|property:definition.source.provider",
  "src/app/api/widgets/batch/route.ts|route|shorthand:route",
  "src/app/api/widgets/batch/route.ts|route|shorthand:route",
  "src/app/api/widgets/batch/route.ts|route|shorthand:route",
  "src/app/api/widgets/batch/route.ts|route|shorthand:route",
  "src/app/api/widgets/batch/route.ts|status|property:batchError.status",
  "src/app/api/widgets/batch/route.ts|status|property:res.status",
  "src/app/api/widgets/daylight/route.ts|fallback|expression:false",
  "src/app/api/widgets/daylight/route.ts|fallback|expression:true",
  "src/app/api/widgets/markets/route.ts|fallback|expression:false",
  "src/app/api/widgets/markets/route.ts|fallback|expression:true",
  "src/app/api/widgets/markets/route.ts|fallback|expression:true",
  "src/app/api/widgets/poem/route.ts|code|property:failure.code",
  "src/app/api/widgets/poem/route.ts|code|property:failure.code",
  "src/app/api/widgets/poem/route.ts|fallback|expression:false",
  "src/app/api/widgets/poem/route.ts|fallback|expression:true",
  "src/app/api/widgets/poem/route.ts|fallback|expression:true",
  "src/app/api/widgets/poem/route.ts|level|ternary:failure.expected ? \"info\" : \"warning\"",
  "src/app/api/widgets/poem/route.ts|shape|spread:expression:(failure.status !== undefined ? { status: String(failure.status) } : {})",
  "src/app/api/widgets/poem/route.ts|shape|spread:expression:(failure.status !== undefined ? { status: failure.status } : {})",
  "src/app/api/widgets/poem/route.ts|shape|spread:identifier:captureContext",
  "src/app/api/widgets/training/route.ts|fallback|expression:!activities",
  "src/app/api/widgets/training/route.ts|fallback|expression:false",
  "src/app/api/widgets/training/route.ts|fallback|expression:true",
  "src/app/api/widgets/weather/route.ts|fallback|expression:false",
  "src/app/api/widgets/weather/route.ts|fallback|expression:true",
  "src/components/agenda/AgendaModule.tsx|supabase_code|expression:error?.code ?? \"unknown\"",
  "src/components/auth/BiometricGate.tsx|status|ternary:pendingFailure.status === null ? 'network' : String(pendingFailure.status)",
  "src/components/layout/Mascot.tsx|operation|shorthand:operation",
  "src/components/layout/Mascot.tsx|route|expression:routeFamily(pathname)",
  "src/components/layout/Mascot.tsx|status|ternary:status ? String(status) : \"unknown\"",
  "src/components/layout/ShellProfileContext.tsx|operation|shorthand:operation",
  "src/components/literature/LiteratureModule.tsx|supabase_code|expression:error.code ?? \"unknown\"",
  "src/components/literature/LiteratureModule.tsx|supabase_code|expression:error.code ?? \"unknown\"",
  "src/components/literature/LiteratureModule.tsx|supabase_code|expression:error.code ?? \"unknown\"",
  "src/components/literature/LiteratureModule.tsx|supabase_code|expression:stageError?.code ?? \"unknown\"",
  "src/components/literature/LiteratureModule.tsx|supabase_code|expression:stagesError.code ?? \"unknown\"",
  "src/components/nav/CommandPalette.tsx|error_code|expression:errorCode ?? \"UNKNOWN\"",
  "src/components/nav/CommandPalette.tsx|http_status|ternary:status ? String(status) : \"unavailable\"",
  "src/components/notes/NotesModule.tsx|supabase_code|expression:error.code ?? \"unknown\"",
  "src/components/notes/NotesModule.tsx|supabase_code|expression:error.code ?? \"unknown\"",
  "src/components/notes/NotesModule.tsx|supabase_code|expression:stageError.code ?? \"unknown\"",
  "src/components/search/SearchWidget.tsx|status|ternary:status ? String(status) : \"network_or_invalid_response\"",
  "src/components/search/SearchWidget.tsx|status|ternary:status ? String(status) : \"network_or_invalid_response\"",
  "src/components/search/SearchWidget.tsx|status|ternary:status ? String(status) : \"network_or_invalid_response\"",
  "src/components/search/SearchWidget.tsx|status|ternary:status ? String(status) : \"network_or_invalid_response\"",
  "src/components/search/SearchWidget.tsx|status|ternary:status ? String(status) : \"network_or_invalid_response\"",
  "src/components/search/SearchWidget.tsx|status|ternary:status ? String(status) : \"network_or_invalid_response\"",
  "src/components/signals/SignalsModule.tsx|op|property:context.op",
  "src/components/signals/SignalsModule.tsx|via|expression:context.via ?? \"none\"",
  "src/components/tasks/TasksModule.tsx|operation|shorthand:operation",
  "src/components/tasks/TasksModule.tsx|shape|spread:expression:(status == null ? {} : { status: String(status) })",
  "src/components/tasks/TasksModule.tsx|status|property:response.status",
  "src/components/theme/ThemeProvider.tsx|operation|shorthand:operation",
  "src/components/theme/ThemeProvider.tsx|shape|spread:identifier:directRead",
  "src/components/vector/GameRuntimeHost.tsx|code|property:failure.code",
  "src/components/vector/GameRuntimeHost.tsx|operation|shorthand:operation",
  "src/components/vector/GameRuntimeHost.tsx|route|template:`vector.game.${manifest.id}`",
  "src/components/vector/GameRuntimeHost.tsx|route|template:`vector.game.${manifest.id}`",
  "src/components/vector/GameRuntimeHost.tsx|status|property:failure.status",
  "src/components/workspace/WorkspaceEntityPane.tsx|status|expression:String(response.status)",
  "src/components/workspace/WorkspaceEntityPane.tsx|status|expression:String(response.status)",
  "src/components/workspace/WorkspaceProvider.tsx|encoded_length|identifier:encodedLength",
  "src/components/workspace/WorkspaceProvider.tsx|error_code|identifier:errorCode",
  "src/components/workspace/WorkspaceProvider.tsx|level|ternary:message.endsWith(\"parse failed\") ? \"warning\" : \"error\"",
  "src/hooks/useVectorOffline.ts|operation|shorthand:operation",
  "src/hooks/useVectorPlatform.ts|code|shorthand:code",
  "src/hooks/useVectorPlatform.ts|operation|shorthand:operation",
  "src/lib/ai/router.ts|code|ternary:rateLimited ? \"PROVIDER_RATE_LIMITED\" : \"PROVIDER_FALLBACK\"",
  "src/lib/ai/router.ts|status|ternary:rateLimited ? 429 : 502",
  "src/lib/ai/workflows.ts|code|ternary:error instanceof z.ZodError ? \"schema_validation\" : \"provider_error\"",
  "src/lib/fund/notifyViaMake.ts|operation|shorthand:operation",
  "src/lib/hooks/useNotes.ts|operation|shorthand:operation",
  "src/lib/hooks/useNotes.ts|status|expression:err?.status ?? null",
  "src/lib/hooks/useNotes.ts|supabase_code|expression:err?.code ?? \"unknown\"",
  "src/lib/hooks/useObjectives.ts|supabase_code|expression:historyError.code ?? \"unknown\"",
  "src/lib/hooks/useTasks.ts|operation|shorthand:operation",
  "src/lib/hooks/useTasks.ts|status|expression:err?.status ?? null",
  "src/lib/hooks/useTasks.ts|supabase_code|expression:err?.code ?? \"unknown\"",
  "src/lib/integrations/make.ts|operation|property:input.operation",
  "src/lib/integrations/make.ts|operation|shorthand:operation",
  "src/lib/integrations/make.ts|shape|spread:expression:(input.init?.headers ?? {})",
  "src/lib/integrations/make.ts|shape|spread:expression:(readOnly ? { retry: { maxAttempts: MAKE_MANAGEMENT_READ_ATTEMPTS, baseDelayMs: 250, maxDelayMs: 1_000, }, } : {})",
  "src/lib/integrations/make.ts|shape|spread:property:input.init",
  "src/lib/massive/client.ts|operation|expression:path.split(\"/\").filter(Boolean).slice(0, 3).join(\"_\") || \"request\"",
  "src/lib/observability/captureRouteError.ts|level|ternary:shouldCapture(opts.status, opts.code) ? \"error\" : \"warning\"",
  "src/lib/observability/providerTiming.ts|area|property:opts.area",
  "src/lib/observability/providerTiming.ts|area|property:opts.area",
  "src/lib/observability/providerTiming.ts|attempt|shorthand:attempt",
  "src/lib/observability/providerTiming.ts|code|shorthand:code",
  "src/lib/observability/providerTiming.ts|code|ternary:error instanceof ProviderTimeoutError ? error.code : \"network\"",
  "src/lib/observability/providerTiming.ts|delayMs|shorthand:delayMs",
  "src/lib/observability/providerTiming.ts|level|ternary:shouldCapture(failure) ? \"error\" : \"warning\"",
  "src/lib/observability/providerTiming.ts|operation|property:opts.operation",
  "src/lib/observability/providerTiming.ts|operation|property:opts.operation",
  "src/lib/observability/providerTiming.ts|provider|property:opts.provider",
  "src/lib/observability/providerTiming.ts|provider|property:opts.provider",
  "src/lib/observability/providerTiming.ts|shape|spread:expression:(failure.code ? { code: failure.code } : {})",
  "src/lib/observability/providerTiming.ts|shape|spread:expression:(failure.status !== undefined ? { status: String(failure.status) } : {})",
  "src/lib/observability/providerTiming.ts|shape|spread:expression:(opts.transport ? { transport: opts.transport } : {})",
  "src/lib/observability/providerTiming.ts|shape|spread:expression:(opts.transport ? { transport: opts.transport } : {})",
  "src/lib/observability/providerTiming.ts|shape|spread:identifier:extra",
  "src/lib/observability/providerTiming.ts|shape|spread:property:opts.tags",
  "src/lib/observability/providerTiming.ts|status|expression:statusFrom(error)",
  "src/lib/observability/providerTiming.ts|status|expression:statusFrom(error)",
  "src/lib/observability/providerTiming.ts|status|property:res.status",
  "src/lib/observability/redactRouteError.ts|operation|expression:opts.operation ?? \"request\"",
  "src/lib/observability/redactRouteError.ts|route|property:opts.route",
  "src/lib/observability/redactRouteError.ts|shape|spread:expression:(opts.area ? { area: opts.area } : {})",
  "src/lib/observability/redactRouteError.ts|shape|spread:expression:(opts.code ? { code: opts.code } : {})",
  "src/lib/observability/redactRouteError.ts|shape|spread:expression:(opts.provider ? { provider: opts.provider } : {})",
  "src/lib/observability/redactRouteError.ts|shape|spread:expression:(opts.tags ? { tags: opts.tags } : {})",
  "src/lib/observability/redactRouteError.ts|status|shorthand:status",
  "src/lib/routines/executor.ts|code|expression:safeRoutineErrorCode(error)",
  "src/lib/routines/executor.ts|operation|shorthand:operation",
  "src/lib/security/safe-fetch-observability.ts|level|ternary:error instanceof SafeFetchError ? \"info\" : \"error\"",
  "src/lib/security/safe-fetch-observability.ts|operation|shorthand:operation",
  "src/lib/security/safe-fetch-observability.ts|operation|shorthand:operation",
  "src/lib/security/safe-fetch-observability.ts|shape|spread:identifier:data",
  "src/lib/security/safe-fetch-observability.ts|shape|spread:property:searchable.data",
  "src/middleware.ts|code|shorthand:code",
];
