import React, { type ReactNode } from "react";
import type { WidgetDefinition } from "@/lib/widgets/types";

const Icon = ({ children }: { children: ReactNode }) => (
  <svg viewBox="0 0 16 16" fill="none" stroke="currentColor" strokeWidth="1.4" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">
    {children}
  </svg>
);

const baseFreshness = {
  staleAfterSeconds: 15 * 60,
  refreshPolicy: "interval" as const,
};

export const WIDGET_REGISTRY = [
  {
    id: "weather",
    label: "Weather",
    category: "Environment",
    ownerModule: "Command",
    icon: <Icon><circle cx="8" cy="8" r="2.8" /><line x1="8" y1="1.5" x2="8" y2="3" /><line x1="8" y1="13" x2="8" y2="14.5" /><line x1="1.5" y1="8" x2="3" y2="8" /><line x1="13" y1="8" x2="14.5" y2="8" /><line x1="3.4" y1="3.4" x2="4.4" y2="4.4" /><line x1="11.6" y1="11.6" x2="12.6" y2="12.6" /><line x1="3.4" y1="12.6" x2="4.4" y2="11.6" /><line x1="11.6" y1="4.4" x2="12.6" y2="3.4" /></Icon>,
    statusDefault: "setup_required",
    source: { provider: "open-meteo", endpoint: "/api/widgets/weather", cacheKey: "weather", requiresAuth: false, requiresLocation: true },
    freshness: baseFreshness,
    primaryAction: { id: "open", label: "Open weather details", kind: "open-drawer" },
    secondaryActions: [{ id: "refresh", label: "Refresh", kind: "refresh" }],
    detail: { type: "drawer", title: "Weather", sections: ["current", "conditions"] },
    renderModes: ["compact", "drawer"],
    sentryArea: "widgets.weather",
  },
  {
    id: "daylight",
    label: "Daylight",
    category: "Environment",
    ownerModule: "Command",
    icon: <Icon><path d="M2 11 a6 6 0 0 1 12 0" /><line x1="8" y1="2.5" x2="8" y2="4" /><line x1="2.4" y1="7" x2="3.7" y2="7.7" /><line x1="13.6" y1="7" x2="12.3" y2="7.7" /><line x1="1" y1="11" x2="15" y2="11" /></Icon>,
    statusDefault: "setup_required",
    source: { provider: "open-meteo", endpoint: "/api/widgets/daylight", cacheKey: "daylight", requiresAuth: false, requiresLocation: true },
    freshness: baseFreshness,
    primaryAction: { id: "open", label: "Open daylight details", kind: "open-drawer" },
    secondaryActions: [{ id: "refresh", label: "Refresh", kind: "refresh" }],
    detail: { type: "drawer", title: "Daylight", sections: ["sunrise", "sunset"] },
    renderModes: ["compact", "drawer"],
    sentryArea: "widgets.daylight",
  },
  {
    id: "air",
    label: "Air Quality",
    category: "Environment",
    ownerModule: "Command",
    icon: <Icon><path d="M2 5.5 h7 a2.5 2.5 0 0 1 0 5" /><path d="M2 8.5 h5 a2 2 0 0 1 0 4" /><line x1="2" y1="11.5" x2="5" y2="11.5" /></Icon>,
    statusDefault: "setup_required",
    source: { provider: "open-meteo", endpoint: "/api/widgets/air-quality", cacheKey: "air", requiresAuth: false, requiresLocation: true },
    freshness: baseFreshness,
    primaryAction: { id: "open", label: "Open air quality details", kind: "open-drawer" },
    secondaryActions: [{ id: "refresh", label: "Refresh", kind: "refresh" }],
    detail: { type: "drawer", title: "Air Quality", sections: ["aqi", "uv"] },
    renderModes: ["compact", "drawer"],
    sentryArea: "widgets.air",
  },
  {
    id: "agenda",
    label: "Agenda",
    category: "Schedule",
    ownerModule: "Agenda",
    icon: <Icon><rect x="2.5" y="3.5" width="11" height="10" rx="1.5" /><line x1="2.5" y1="7" x2="13.5" y2="7" /><line x1="5.5" y1="2" x2="5.5" y2="5" /><line x1="10.5" y1="2" x2="10.5" y2="5" /></Icon>,
    statusDefault: "empty",
    source: { provider: "supabase", endpoint: "/api/widgets/agenda", cacheKey: "agenda", requiresAuth: true },
    freshness: baseFreshness,
    primaryAction: { id: "open", label: "Open Agenda", kind: "navigate", href: "/agenda" },
    secondaryActions: [{ id: "refresh", label: "Refresh", kind: "refresh" }],
    detail: { type: "route", title: "Agenda", route: "/agenda" },
    renderModes: ["compact", "wide"],
    sentryArea: "widgets.agenda",
  },
  {
    id: "markets",
    label: "Markets",
    category: "Finance",
    ownerModule: "Fund",
    icon: <Icon><polyline points="2,12 5.5,8.5 8.5,10 13.5,4.5" /><polyline points="10.5,4.5 13.5,4.5 13.5,7.5" /></Icon>,
    statusDefault: "setup_required",
    source: { provider: "polygon", endpoint: "/api/widgets/markets", cacheKey: "markets", requiresAuth: false },
    freshness: baseFreshness,
    primaryAction: { id: "open", label: "Open markets", kind: "navigate", href: "/fund/market" },
    secondaryActions: [{ id: "refresh", label: "Refresh", kind: "refresh" }],
    detail: { type: "route", title: "Markets", route: "/fund/market" },
    renderModes: ["compact", "wide"],
    sentryArea: "widgets.markets",
  },
  {
    id: "run",
    label: "Training",
    category: "Health",
    ownerModule: "Vitality",
    icon: <Icon><polyline points="9.5,2 5,9 8.5,9 6.5,14 12,7 8.5,7" /></Icon>,
    statusDefault: "disconnected",
    source: { provider: "strava", endpoint: "/api/widgets/training", cacheKey: "run", requiresAuth: true, requiresConnection: "strava" },
    freshness: baseFreshness,
    primaryAction: { id: "open", label: "Open Vitality", kind: "navigate", href: "/vitality" },
    secondaryActions: [{ id: "refresh", label: "Refresh", kind: "refresh" }],
    detail: { type: "route", title: "Training", route: "/vitality" },
    renderModes: ["compact", "wide"],
    sentryArea: "widgets.training",
  },
  {
    id: "sleep",
    label: "Sleep",
    category: "Health",
    ownerModule: "Vitality",
    icon: <Icon><path d="M12.5 11.5 A5.5 5.5 0 1 1 4.5 3.5 A4 4 0 0 0 12.5 11.5Z" /></Icon>,
    statusDefault: "lab",
    source: { provider: "none", cacheKey: "sleep", requiresAuth: false, requiresConnection: "wearable" },
    freshness: { staleAfterSeconds: 0, refreshPolicy: "manual" },
    primaryAction: { id: "open", label: "Open Vitality", kind: "navigate", href: "/vitality" },
    secondaryActions: [],
    detail: { type: "route", title: "Sleep", route: "/vitality" },
    renderModes: ["compact"],
    sentryArea: "widgets.sleep",
  },
  {
    id: "hrv",
    label: "HRV",
    category: "Health",
    ownerModule: "Vitality",
    icon: <Icon><polyline points="1,8 4,8 5.5,5 7,11 8.5,6.5 10,9.5 11.5,8 15,8" /></Icon>,
    statusDefault: "lab",
    source: { provider: "none", cacheKey: "hrv", requiresAuth: false, requiresConnection: "wearable" },
    freshness: { staleAfterSeconds: 0, refreshPolicy: "manual" },
    primaryAction: { id: "open", label: "Open Vitality", kind: "navigate", href: "/vitality" },
    secondaryActions: [],
    detail: { type: "route", title: "HRV", route: "/vitality" },
    renderModes: ["compact"],
    sentryArea: "widgets.hrv",
  },
  {
    id: "heartrate",
    label: "Resting HR",
    category: "Health",
    ownerModule: "Vitality",
    icon: <Icon><path d="M8 13 C6 11 2 8.5 2 5.5 A3 3 0 0 1 8 4.2 A3 3 0 0 1 14 5.5 C14 8.5 10 11 8 13Z" /></Icon>,
    statusDefault: "lab",
    source: { provider: "none", cacheKey: "heartrate", requiresAuth: false, requiresConnection: "wearable" },
    freshness: { staleAfterSeconds: 0, refreshPolicy: "manual" },
    primaryAction: { id: "open", label: "Open Vitality", kind: "navigate", href: "/vitality" },
    secondaryActions: [],
    detail: { type: "route", title: "Resting HR", route: "/vitality" },
    renderModes: ["compact"],
    sentryArea: "widgets.heartrate",
  },
  {
    id: "vo2max",
    label: "VO2 Max",
    category: "Health",
    ownerModule: "Vitality",
    icon: <Icon><path d="M8 4 v8" /><path d="M8 6.5 C8 6.5 4.5 6.5 4.5 9.5 C4.5 11.5 6 12.5 8 11.5" /><path d="M8 6.5 C8 6.5 11.5 6.5 11.5 9.5 C11.5 11.5 10 12.5 8 11.5" /></Icon>,
    statusDefault: "lab",
    source: { provider: "none", cacheKey: "vo2max", requiresAuth: false, requiresConnection: "wearable" },
    freshness: { staleAfterSeconds: 0, refreshPolicy: "manual" },
    primaryAction: { id: "open", label: "Open Vitality", kind: "navigate", href: "/vitality" },
    secondaryActions: [],
    detail: { type: "route", title: "VO2 Max", route: "/vitality" },
    renderModes: ["compact"],
    sentryArea: "widgets.vo2max",
  },
  {
    id: "hydration",
    label: "Hydration",
    category: "Wellness",
    ownerModule: "Vitality",
    icon: <Icon><path d="M8 2 C8 2 3.5 8 3.5 11 A4.5 4.5 0 0 0 12.5 11 C12.5 8 8 2 8 2Z" /></Icon>,
    statusDefault: "lab",
    source: { provider: "manual", cacheKey: "hydration", requiresAuth: true },
    freshness: { staleAfterSeconds: 0, refreshPolicy: "manual" },
    primaryAction: { id: "open", label: "Open Vitality", kind: "navigate", href: "/vitality" },
    secondaryActions: [],
    detail: { type: "route", title: "Hydration", route: "/vitality" },
    renderModes: ["compact"],
    sentryArea: "widgets.hydration",
  },
  {
    id: "location",
    label: "Location",
    category: "Environment",
    ownerModule: "Command",
    icon: <Icon><path d="M8 1.5 A4 4 0 0 1 12 5.5 C12 9 8 14.5 8 14.5 C8 14.5 4 9 4 5.5 A4 4 0 0 1 8 1.5Z" /><circle cx="8" cy="5.5" r="1.5" fill="currentColor" stroke="none" /></Icon>,
    statusDefault: "setup_required",
    source: { provider: "browser", cacheKey: "location", requiresAuth: false, requiresLocation: true },
    freshness: { staleAfterSeconds: 0, refreshPolicy: "on-focus" },
    primaryAction: { id: "open", label: "Open location details", kind: "open-drawer" },
    secondaryActions: [{ id: "refresh", label: "Refresh", kind: "refresh" }],
    detail: { type: "drawer", title: "Location", sections: ["coordinates", "permission"] },
    renderModes: ["compact", "drawer"],
    sentryArea: "widgets.location",
  },
] satisfies WidgetDefinition[];

export type WidgetId = (typeof WIDGET_REGISTRY)[number]["id"];

export function getWidgetDefinition(id: string): WidgetDefinition | undefined {
  return WIDGET_REGISTRY.find((widget) => widget.id === id);
}

export function requireWidgetDefinition(id: string): WidgetDefinition {
  const widget = getWidgetDefinition(id);
  if (!widget) throw new Error(`Unknown widget id: ${id}`);
  return widget;
}
