/** Calendar-related Composio tool slugs — single source for calendar adapters. */
export const GOOGLECALENDAR_COMPOSIO_TOOLS = [
  "GOOGLECALENDAR_EVENTS_LIST",
  "GOOGLECALENDAR_CREATE_EVENT",
  "GOOGLECALENDAR_DELETE_EVENT",
  "GOOGLECALENDAR_FREE_BUSY_QUERY",
  "GOOGLECALENDAR_FIND_FREE_SLOTS",
  "GOOGLECALENDAR_LIST_CALENDARS",
] as const;

export const OUTLOOK_CALENDAR_COMPOSIO_TOOLS = [
  "OUTLOOK_LIST_EVENTS",
  "OUTLOOK_CALENDAR_CREATE_EVENT",
  "OUTLOOK_DELETE_EVENT",
] as const;

export const CALENDAR_COMPOSIO_TOOLS = {
  googlecalendar: GOOGLECALENDAR_COMPOSIO_TOOLS,
  outlook: OUTLOOK_CALENDAR_COMPOSIO_TOOLS,
} as const;
