-- Wrap auth.uid() in (select ...) across all per-row RLS policies so Postgres
-- can initplan it once per query instead of re-evaluating per row.
ALTER POLICY "board_fields_delete_own" ON public.board_fields USING (((select auth.uid()) = user_id));
ALTER POLICY "board_fields_insert_own" ON public.board_fields WITH CHECK (((select auth.uid()) = user_id));
ALTER POLICY "board_fields_select_own" ON public.board_fields USING (((select auth.uid()) = user_id));
ALTER POLICY "board_fields_update_own" ON public.board_fields USING (((select auth.uid()) = user_id)) WITH CHECK (((select auth.uid()) = user_id));
ALTER POLICY "Users manage own calendar connections" ON public.calendar_connections USING (((select auth.uid()) = user_id)) WITH CHECK (((select auth.uid()) = user_id));
ALTER POLICY "conferences_delete_own" ON public.conferences USING (((select auth.uid()) = user_id));
ALTER POLICY "conferences_insert_own" ON public.conferences WITH CHECK (((select auth.uid()) = user_id));
ALTER POLICY "conferences_select_own" ON public.conferences USING (((select auth.uid()) = user_id));
ALTER POLICY "conferences_update_own" ON public.conferences USING (((select auth.uid()) = user_id)) WITH CHECK (((select auth.uid()) = user_id));
ALTER POLICY "console_photos_delete_own" ON public.console_photos USING (((select auth.uid()) = user_id));
ALTER POLICY "console_photos_insert_own" ON public.console_photos WITH CHECK (((select auth.uid()) = user_id));
ALTER POLICY "console_photos_select_own" ON public.console_photos USING (((select auth.uid()) = user_id));
ALTER POLICY "console_photos_update_own" ON public.console_photos USING (((select auth.uid()) = user_id)) WITH CHECK (((select auth.uid()) = user_id));
ALTER POLICY "console_widgets_delete_own" ON public.console_widgets USING (((select auth.uid()) = user_id));
ALTER POLICY "console_widgets_insert_own" ON public.console_widgets WITH CHECK (((select auth.uid()) = user_id));
ALTER POLICY "console_widgets_select_own" ON public.console_widgets USING (((select auth.uid()) = user_id));
ALTER POLICY "console_widgets_update_own" ON public.console_widgets USING (((select auth.uid()) = user_id)) WITH CHECK (((select auth.uid()) = user_id));
ALTER POLICY "owner only" ON public.contacts_connections USING (((select auth.uid()) = user_id)) WITH CHECK (((select auth.uid()) = user_id));
ALTER POLICY "fitness_routine_exercises_delete_own" ON public.fitness_routine_exercises USING (((select auth.uid()) = user_id));
ALTER POLICY "fitness_routine_exercises_insert_own" ON public.fitness_routine_exercises WITH CHECK (((select auth.uid()) = user_id));
ALTER POLICY "fitness_routine_exercises_select_own" ON public.fitness_routine_exercises USING (((select auth.uid()) = user_id));
ALTER POLICY "fitness_routine_exercises_update_own" ON public.fitness_routine_exercises USING (((select auth.uid()) = user_id)) WITH CHECK (((select auth.uid()) = user_id));
ALTER POLICY "fitness_routines_delete_own" ON public.fitness_routines USING (((select auth.uid()) = user_id));
ALTER POLICY "fitness_routines_insert_own" ON public.fitness_routines WITH CHECK (((select auth.uid()) = user_id));
ALTER POLICY "fitness_routines_select_own" ON public.fitness_routines USING (((select auth.uid()) = user_id));
ALTER POLICY "fitness_routines_update_own" ON public.fitness_routines USING (((select auth.uid()) = user_id)) WITH CHECK (((select auth.uid()) = user_id));
ALTER POLICY "fund_connections_delete_own" ON public.fund_connections USING (((select auth.uid()) = user_id));
ALTER POLICY "fund_connections_insert_own" ON public.fund_connections WITH CHECK (((select auth.uid()) = user_id));
ALTER POLICY "fund_connections_select_own" ON public.fund_connections USING (((select auth.uid()) = user_id));
ALTER POLICY "fund_connections_update_own" ON public.fund_connections USING (((select auth.uid()) = user_id)) WITH CHECK (((select auth.uid()) = user_id));
ALTER POLICY "fund_holdings_delete_own" ON public.fund_holdings USING (((select auth.uid()) = user_id));
ALTER POLICY "fund_holdings_insert_own" ON public.fund_holdings WITH CHECK (((select auth.uid()) = user_id));
ALTER POLICY "fund_holdings_select_own" ON public.fund_holdings USING (((select auth.uid()) = user_id));
ALTER POLICY "fund_holdings_update_own" ON public.fund_holdings USING (((select auth.uid()) = user_id)) WITH CHECK (((select auth.uid()) = user_id));
ALTER POLICY "fund_transactions_delete_own" ON public.fund_transactions USING (((select auth.uid()) = user_id));
ALTER POLICY "fund_transactions_insert_own" ON public.fund_transactions WITH CHECK (((select auth.uid()) = user_id));
ALTER POLICY "fund_transactions_select_own" ON public.fund_transactions USING (((select auth.uid()) = user_id));
ALTER POLICY "fund_transactions_update_own" ON public.fund_transactions USING (((select auth.uid()) = user_id)) WITH CHECK (((select auth.uid()) = user_id));
ALTER POLICY "fund_watchlist_delete_own" ON public.fund_watchlist USING (((select auth.uid()) = user_id));
ALTER POLICY "fund_watchlist_insert_own" ON public.fund_watchlist WITH CHECK (((select auth.uid()) = user_id));
ALTER POLICY "fund_watchlist_select_own" ON public.fund_watchlist USING (((select auth.uid()) = user_id));
ALTER POLICY "fund_watchlist_update_own" ON public.fund_watchlist USING (((select auth.uid()) = user_id)) WITH CHECK (((select auth.uid()) = user_id));
ALTER POLICY "Users can manage own gallery favorites" ON public.gallery_favorites USING (((select auth.uid()) = user_id)) WITH CHECK (((select auth.uid()) = user_id));
ALTER POLICY "habit_checks_delete_own" ON public.habit_checks USING (((select auth.uid()) = user_id));
ALTER POLICY "habit_checks_insert_own" ON public.habit_checks WITH CHECK (((select auth.uid()) = user_id));
ALTER POLICY "habit_checks_select_own" ON public.habit_checks USING (((select auth.uid()) = user_id));
ALTER POLICY "habits_delete_own" ON public.habits USING (((select auth.uid()) = user_id));
ALTER POLICY "habits_insert_own" ON public.habits WITH CHECK (((select auth.uid()) = user_id));
ALTER POLICY "habits_select_own" ON public.habits USING (((select auth.uid()) = user_id));
ALTER POLICY "habits_update_own" ON public.habits USING (((select auth.uid()) = user_id)) WITH CHECK (((select auth.uid()) = user_id));
ALTER POLICY "key_results_delete_own" ON public.key_results USING (((select auth.uid()) = user_id));
ALTER POLICY "key_results_insert_own" ON public.key_results WITH CHECK (((select auth.uid()) = user_id));
ALTER POLICY "key_results_select_own" ON public.key_results USING (((select auth.uid()) = user_id));
ALTER POLICY "key_results_update_own" ON public.key_results USING (((select auth.uid()) = user_id)) WITH CHECK (((select auth.uid()) = user_id));
ALTER POLICY "Users can manage own library files" ON public.library_files USING (((select auth.uid()) = user_id)) WITH CHECK (((select auth.uid()) = user_id));
ALTER POLICY "literature_prefs_insert_own" ON public.literature_prefs WITH CHECK (((select auth.uid()) = user_id));
ALTER POLICY "literature_prefs_select_own" ON public.literature_prefs USING (((select auth.uid()) = user_id));
ALTER POLICY "literature_prefs_update_own" ON public.literature_prefs USING (((select auth.uid()) = user_id)) WITH CHECK (((select auth.uid()) = user_id));
ALTER POLICY "literature_saved_delete_own" ON public.literature_saved USING (((select auth.uid()) = user_id));
ALTER POLICY "literature_saved_insert_own" ON public.literature_saved WITH CHECK (((select auth.uid()) = user_id));
ALTER POLICY "literature_saved_select_own" ON public.literature_saved USING (((select auth.uid()) = user_id));
ALTER POLICY "mail_connections_own" ON public.mail_connections USING (((select auth.uid()) = user_id));
ALTER POLICY "moodboard_images_delete_own" ON public.moodboard_images USING (((select auth.uid()) = user_id));
ALTER POLICY "moodboard_images_insert_own" ON public.moodboard_images WITH CHECK (((select auth.uid()) = user_id));
ALTER POLICY "moodboard_images_select_own" ON public.moodboard_images USING (((select auth.uid()) = user_id));
ALTER POLICY "moodboard_images_update_own" ON public.moodboard_images USING (((select auth.uid()) = user_id)) WITH CHECK (((select auth.uid()) = user_id));
ALTER POLICY "net_worth_snapshots_delete_own" ON public.net_worth_snapshots USING (((select auth.uid()) = user_id));
ALTER POLICY "net_worth_snapshots_insert_own" ON public.net_worth_snapshots WITH CHECK (((select auth.uid()) = user_id));
ALTER POLICY "net_worth_snapshots_select_own" ON public.net_worth_snapshots USING (((select auth.uid()) = user_id));
ALTER POLICY "net_worth_snapshots_update_own" ON public.net_worth_snapshots USING (((select auth.uid()) = user_id)) WITH CHECK (((select auth.uid()) = user_id));
ALTER POLICY "owner only" ON public.note_embeddings USING (((select auth.uid()) = user_id)) WITH CHECK (((select auth.uid()) = user_id));
ALTER POLICY "notes_delete_own" ON public.notes USING (((select auth.uid()) = user_id));
ALTER POLICY "notes_insert_own" ON public.notes WITH CHECK (((select auth.uid()) = user_id));
ALTER POLICY "notes_select_own" ON public.notes USING (((select auth.uid()) = user_id));
ALTER POLICY "notes_update_own" ON public.notes USING (((select auth.uid()) = user_id)) WITH CHECK (((select auth.uid()) = user_id));
ALTER POLICY "nutrition_protocol_delete_own" ON public.nutrition_protocol USING (((select auth.uid()) = user_id));
ALTER POLICY "nutrition_protocol_insert_own" ON public.nutrition_protocol WITH CHECK (((select auth.uid()) = user_id));
ALTER POLICY "nutrition_protocol_select_own" ON public.nutrition_protocol USING (((select auth.uid()) = user_id));
ALTER POLICY "nutrition_protocol_update_own" ON public.nutrition_protocol USING (((select auth.uid()) = user_id)) WITH CHECK (((select auth.uid()) = user_id));
ALTER POLICY "objectives_delete_own" ON public.objectives USING (((select auth.uid()) = user_id));
ALTER POLICY "objectives_insert_own" ON public.objectives WITH CHECK (((select auth.uid()) = user_id));
ALTER POLICY "objectives_select_own" ON public.objectives USING (((select auth.uid()) = user_id));
ALTER POLICY "objectives_update_own" ON public.objectives USING (((select auth.uid()) = user_id)) WITH CHECK (((select auth.uid()) = user_id));
ALTER POLICY "people_delete_own" ON public.people USING (((select auth.uid()) = user_id));
ALTER POLICY "people_insert_own" ON public.people WITH CHECK (((select auth.uid()) = user_id));
ALTER POLICY "people_select_own" ON public.people USING (((select auth.uid()) = user_id));
ALTER POLICY "people_update_own" ON public.people USING (((select auth.uid()) = user_id)) WITH CHECK (((select auth.uid()) = user_id));
ALTER POLICY "pipeline_stages_delete_own" ON public.pipeline_stages USING (((select auth.uid()) = user_id));
ALTER POLICY "pipeline_stages_insert_own" ON public.pipeline_stages WITH CHECK (((select auth.uid()) = user_id));
ALTER POLICY "pipeline_stages_select_own" ON public.pipeline_stages USING (((select auth.uid()) = user_id));
ALTER POLICY "pipeline_stages_update_own" ON public.pipeline_stages USING (((select auth.uid()) = user_id)) WITH CHECK (((select auth.uid()) = user_id));
ALTER POLICY "profiles_insert_own" ON public.profiles WITH CHECK (((select auth.uid()) = id));
ALTER POLICY "profiles_select_own" ON public.profiles USING (((select auth.uid()) = id));
ALTER POLICY "profiles_update_own" ON public.profiles USING (((select auth.uid()) = id)) WITH CHECK (((select auth.uid()) = id));
ALTER POLICY "schedule_events_delete_own" ON public.schedule_events USING (((select auth.uid()) = user_id));
ALTER POLICY "schedule_events_insert_own" ON public.schedule_events WITH CHECK (((select auth.uid()) = user_id));
ALTER POLICY "schedule_events_select_own" ON public.schedule_events USING (((select auth.uid()) = user_id));
ALTER POLICY "schedule_events_update_own" ON public.schedule_events USING (((select auth.uid()) = user_id)) WITH CHECK (((select auth.uid()) = user_id));
ALTER POLICY "signal_routes_delete_own" ON public.signal_routes USING (((select auth.uid()) = user_id));
ALTER POLICY "signal_routes_insert_own" ON public.signal_routes WITH CHECK (((select auth.uid()) = user_id));
ALTER POLICY "signal_routes_select_own" ON public.signal_routes USING (((select auth.uid()) = user_id));
ALTER POLICY "signal_routes_update_own" ON public.signal_routes USING (((select auth.uid()) = user_id)) WITH CHECK (((select auth.uid()) = user_id));
ALTER POLICY "signals_delete_own" ON public.signals USING (((select auth.uid()) = user_id));
ALTER POLICY "signals_insert_own" ON public.signals WITH CHECK (((select auth.uid()) = user_id));
ALTER POLICY "signals_select_own" ON public.signals USING (((select auth.uid()) = user_id));
ALTER POLICY "signals_update_own" ON public.signals USING (((select auth.uid()) = user_id)) WITH CHECK (((select auth.uid()) = user_id));
ALTER POLICY "studies_delete_own" ON public.studies USING (((select auth.uid()) = user_id));
ALTER POLICY "studies_insert_own" ON public.studies WITH CHECK (((select auth.uid()) = user_id));
ALTER POLICY "studies_select_own" ON public.studies USING (((select auth.uid()) = user_id));
ALTER POLICY "studies_update_own" ON public.studies USING (((select auth.uid()) = user_id)) WITH CHECK (((select auth.uid()) = user_id));
ALTER POLICY "tasks_delete_own" ON public.tasks USING (((select auth.uid()) = user_id));
ALTER POLICY "tasks_insert_own" ON public.tasks WITH CHECK (((select auth.uid()) = user_id));
ALTER POLICY "tasks_select_own" ON public.tasks USING (((select auth.uid()) = user_id));
ALTER POLICY "tasks_update_own" ON public.tasks USING (((select auth.uid()) = user_id)) WITH CHECK (((select auth.uid()) = user_id));
ALTER POLICY "training_sessions_delete_own" ON public.training_sessions USING (((select auth.uid()) = user_id));
ALTER POLICY "training_sessions_insert_own" ON public.training_sessions WITH CHECK (((select auth.uid()) = user_id));
ALTER POLICY "training_sessions_select_own" ON public.training_sessions USING (((select auth.uid()) = user_id));
ALTER POLICY "training_sessions_update_own" ON public.training_sessions USING (((select auth.uid()) = user_id)) WITH CHECK (((select auth.uid()) = user_id));
ALTER POLICY "Users manage own auth settings" ON public.user_auth_settings USING (((select auth.uid()) = user_id));
ALTER POLICY "Users manage own passkeys" ON public.user_passkeys USING (((select auth.uid()) = user_id));
ALTER POLICY "user_preferences_insert_own" ON public.user_preferences WITH CHECK (((select auth.uid()) = user_id));
ALTER POLICY "user_preferences_select_own" ON public.user_preferences USING (((select auth.uid()) = user_id));
ALTER POLICY "user_preferences_update_own" ON public.user_preferences USING (((select auth.uid()) = user_id)) WITH CHECK (((select auth.uid()) = user_id));
ALTER POLICY "strava_tokens_delete_own" ON public.user_strava_tokens USING (((select auth.uid()) = user_id));
ALTER POLICY "strava_tokens_insert_own" ON public.user_strava_tokens WITH CHECK (((select auth.uid()) = user_id));
ALTER POLICY "strava_tokens_select_own" ON public.user_strava_tokens USING (((select auth.uid()) = user_id));
ALTER POLICY "strava_tokens_update_own" ON public.user_strava_tokens USING (((select auth.uid()) = user_id)) WITH CHECK (((select auth.uid()) = user_id));
